# Which docker image should be used to deploy
DOCKER_TAG: ""
# This option turns on or off logging in graylog
GRAYLOG_ON: "false"
# Keycloak enabled
KEYCLOAK_ENABLED: "false"
# Spring profile for security
SPRING_PROFILES: "disable-security"
keepHookLogs: true
HELPER_IMAGE: "ghcr.io/netcracker/qubership-testing-platform-helm-hook-helper:main_latest"
CONTENT_SECURITY_POLICY: "*"
MONGO_DB_ADDR: ""
EDS_GRIDFS_ENABLED: "false"
EI_GRIDFS_ENABLED: "false"
HAZELCAST_CACHE_ENABLED: "false"
EUREKA_CLIENT_ENABLED: "false"
ATP_INTEGRATION_ENABLED: "false"
ATP_SERVICE_PUBLIC: "false"
TLS_ENABLED: "false"
ATP_ITF_BROKER_URL_TCP: "tcp://activemq-broker:61616"
ACTIVEMQ_PORT_PARAM: "61616"
ATP_INTERNAL_GATEWAY_ENABLED: "false"
START_TRANSPORT_TRIGGERS_AT_STARTUP: "false"
TRIGGERS_ACTIVATION_SYNC: "false"
